import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { PostCard, Categories, PostWidget } from "../components";
import { getPosts } from "../service";
export default function Home({ posts }) {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Jaran Blog</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid grid-cols-1 lg:grid-cols-12 gap-12">
        <section className="lg:col-span-8 col-span-1">
          {posts.map((item, key) => (
            <PostCard posts={item} key={key} />
          ))}
        </section>
        <section className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8">
            <PostWidget />
            <Categories />
          </div>
        </section>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return {
    props: { posts },
  };
}
